services:
  - type: web
    name: image-to-manim
    env: docker
    dockerfilePath: ./Dockerfile
    plan: standard
    healthCheckPath: /health
    envVars:
      - key: DEEPINFRA_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
